CANVAS_WIDTH = 600
CANVAS_HEIGHT = 400

WINDOW_WIDTH = 1400
WINDOW_HEIGHT = 840

A4_WIDTH_MM = 210
A4_HEIGHT_MM = 297

CANVAS_SIZE_SCALER = 2.7

DEFAULT_LABELLED_SLIDER_WIDTH = 200
DEFAULT_LABELLED_SLIDER_HEIGHT = 80

DEFAULT_PICTURE_WIDTH = 50
DEFAULT_PICTURE_HEIGHT = 50

DEFAULT_MONO_THRESHOLD = 100
MINIMUM_THRESHOLD = 1
MAXIMUM_THRESHOLD = 255

DIRECTIONS = [(-1, 0), (1, 0), (0, -1), (0, 1),
              (-1, -1), (-1, 1), (1, -1), (1, 1)]

COLOR_RANDOMNESS = 50

STEPS_PER_MILLIMETER_X = 20
STEPS_PER_MILLIMETER_Y = 20

A4_WIDTH_STEPS = A4_WIDTH_MM * STEPS_PER_MILLIMETER_X
A4_HEIGHT_STEPS = A4_HEIGHT_MM * STEPS_PER_MILLIMETER_Y

PATH_COMMANDS = ["up", "down"]
